### ISSUE TITLE
Testing with appium

### ISSUE THREAD

**Issue by thanglyphan** [react-native-webrtc/react-native-callkeep#153]
Is anyone using this library with Appium? If so, how do i test the library by using Appium?

**Comment by manuquentin** [comment]
Hi @thanglyphan,
We use [Detox](https://github.com/wix/Detox) to test our app. We've also added a couple of `adb` command to navigate through Android settings to enable phone account or make call from the native app.

We're not able for now to test it on iOS due to the restriction from Apple to stick to the tested application. So when we test our app, we can put it in background to check if callkit is displayed.

**Comment by manuquentin** [comment]
@thanglyphan can we close this issue ?
